name: Debug Activities HTML

on:
  workflow_dispatch:
    inputs:
      only:
        description: "Institución a inspeccionar (picasso/thyssen/pompidou/all)"
        required: false
        default: "picasso"

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run debug fetch
        run: |
          python scripts/debug_fetch.py --only "${{ github.event.inputs.only }}"

      - name: Auto-commit debug artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(debug): capture activities HTML (${{ github.event.inputs.only }})"
          file_pattern: data/debug/**
          push_options: '--force-with-lease'
